import assert from 'node:assert/strict';
import {RunClip,encodeClip} from '../public/replay-clip.mjs';
let stopped=0,closed=0;const ctx={fillRect(){},drawImage(){},fillText(){}};
const elements=new Map();const element=()=>({hidden:false,addEventListener(){},close(){},load(){},removeAttribute(){},pause(){},showModal(){},play:()=>Promise.resolve()});
globalThis.location={host:'game.example'};
globalThis.document={getElementById(id){if(!elements.has(id))elements.set(id,element());return elements.get(id)},createElement(){return{width:720,height:450,getContext:()=>ctx,toBlob:cb=>cb(new Blob(['frame'])),captureStream:()=>({getTracks:()=>[{stop(){stopped++}}]})}}};
globalThis.createImageBitmap=async()=>({close(){closed++}});
globalThis.MediaRecorder=class {static isTypeSupported(type){return type==='video/webm'}constructor(stream,options){this.mimeType=options.mimeType;this.state='inactive'}start(){this.state='recording'}stop(){this.state='inactive';this.ondataavailable?.({data:new Blob(['video'])});this.onstop?.()}};
const clip=new RunClip();for(let i=0;i<100;i++){clip.capture({width:1440,height:900},i*.11,100);await clip.pending}assert(clip.frames.length<=51);assert(clip.frames.at(-1).time-clip.frames[0].time<=5);clip.finish();assert.equal(clip.button.hidden,false);clip.reset();assert.equal(clip.frames.length,0);assert.equal(clip.button.hidden,true);
const blob=await encodeClip([{time:0,blob:new Blob(['a'])},{time:.2,blob:new Blob(['b'])}],new AbortController().signal);assert(blob.size>0);assert.equal(stopped,1);assert.equal(closed,2);
const controller=new AbortController();controller.abort();await assert.rejects(()=>encodeClip([{time:0},{time:.2}],controller.signal),{name:'AbortError'});
console.log('PASS: bounded replay buffer, reset, format fallback, export and resource cleanup, cancellation.');
