import { Crossing, seededRandom } from '../public/engine.mjs';
import { assets } from './assets.generated.mjs';
const DAY=86400000, SOURCE='https://www.imo.org/en/mediacentre/hottopics/pages/middle-east-strait-of-hormuz.aspx';
const json=(body,status=200,headers={})=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...headers}});
const db=env=>{if(!env.DB)throw new Error('Database unavailable');return env.DB};
const validMode=m=>m==='run'||m==='block';
function playerId(request){return request.headers.get('Cookie')?.match(/(?:^|;\s*)hormuz_player=([a-f0-9-]{36})(?:;|$)/)?.[1]??null}
function dayString(t=Date.now()){return new Date(t).toISOString().slice(0,10)}
function dailySeed(day,mode){let h=2166136261;for(const c of day+mode+'hormuz-v3'){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
async function body(request){if(Number(request.headers.get('Content-Length'))>650000)throw new Error('Request too large');const raw=await request.text();if(raw.length>650000)throw new Error('Request too large');return JSON.parse(raw)}
export function replay(seed,mode,records,total){if(!Number.isInteger(total)||total<1||total>6302||!Array.isArray(records)||records.length>16000)throw new Error('Invalid replay');const g=new Crossing(seededRandom(seed));g.reset(mode);let cursor=0,previous=-1;for(const r of records){if(!Array.isArray(r)||!Number.isInteger(r[0])||r[0]<previous||r[0]<0||r[0]>=total)throw new Error('Invalid replay order');previous=r[0]}
 for(let tick=0;tick<total;tick++){while(cursor<records.length&&records[cursor][0]===tick){const[,kind,value]=records[cursor++];if(kind==='u'){if(g.phase!=='upgrade')throw new Error('Invalid upgrade timing');g.upgrade(value)}else if(kind==='a'){g.ability()}else if(kind==='i'){if(!Array.isArray(value)||value.length!==6||!value.slice(0,4).every(Number.isFinite)||Math.abs(value[0])>1||Math.abs(value[1])>1||![0,1].includes(value[2])||![0,1].includes(value[3]))throw new Error('Invalid controls');const[x,z,boost,fire,ax,az]=value;if((ax===null)!==(az===null)||ax!==null&&(!Number.isFinite(ax)||!Number.isFinite(az)||Math.abs(ax)>500||Math.abs(az)>500))throw new Error('Invalid aim');g.input={x,z,boost:!!boost,fire:!!fire,aim:ax===null?null:{x:ax,z:az}}}else throw new Error('Unknown replay action')}
 if(g.phase!=='play')throw new Error('Replay continues outside gameplay');g.tick(1/60);g.events=[];}
 if(g.phase!=='end')throw new Error('Round is incomplete');return g;
}
export function classifyStatus(html,checkedAt=new Date().toISOString()){
 const text=html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&#160;|&nbsp;|&#8239;/g,' ').replace(/\s+/g,' ');
 const start=text.indexOf('Information related to shipping and seafarers');const intro=start>=0?text.slice(start,start+2200):'';
 const disrupted=/stranded on vessels unable to exit the Strait of Hormuz/i.test(intro);
 return {status:disrupted?'disrupted':'unverified',label:disrupted?'Disrupted':'Unverified',detail:disrupted?'IMO reports ships stranded in the region and unable to exit the strait. This does not mean all traffic has stopped.':'The current official page does not provide a clear open/closed status.',source:'IMO',sourceUrl:SOURCE,checkedAt,sourceDate:text.match(/(\d{1,2} [A-Z][a-z]+ 202\d)\s+Seafarers/)?.[1]??null};
}
let statusCache=null;
async function straitStatus(){if(statusCache&&Date.now()-statusCache.at<600000)return statusCache.value;try{const r=await fetch(SOURCE,{headers:{'User-Agent':'IsHormuzOpen/1.0 (official status summary)'},signal:AbortSignal.timeout(8000)});if(!r.ok)throw new Error('Source unavailable');const value=classifyStatus(await r.text());statusCache={at:Date.now(),value};return value}catch{return {status:'unavailable',label:'Unavailable',detail:'The official source could not be checked. Last-known conditions are not shown as current.',source:'IMO',sourceUrl:SOURCE,checkedAt:null,sourceDate:null}}}
export default {async fetch(request,env){const url=new URL(request.url);try{
 if(url.pathname==='/api/status'&&request.method==='GET')return json(await straitStatus());
 if(url.pathname==='/api/leaderboard'&&request.method==='GET'){const mode=url.searchParams.get('mode');if(!validMode(mode))return json({error:'Choose a mission.'},400);const start=Math.floor(Date.now()/DAY)*DAY;const rows=await db(env).prepare('SELECT name, score, duration, won FROM scores WHERE mode = ? AND created_at >= ? AND created_at < ? ORDER BY score DESC, created_at ASC LIMIT 10').bind(mode,start,start+DAY).all();return json({day:dayString(),mode,entries:rows.results??[]})}
 if(url.pathname.startsWith('/api/')&&request.method==='POST'){
  const origin=request.headers.get('Origin');if(origin&&origin!==url.origin||request.headers.get('Sec-Fetch-Site')==='cross-site')return json({error:'Invalid request origin.'},403);
  if(!request.headers.get('Content-Type')?.includes('application/json'))return json({error:'JSON required.'},415);
  if(url.pathname==='/api/runs'){const data=await body(request);if(!validMode(data.mode))return json({error:'Choose a mission.'},400);const player=playerId(request)??crypto.randomUUID(),now=Date.now();const recent=await db(env).prepare('SELECT COUNT(*) AS count FROM runs WHERE player_id = ? AND created_at > ?').bind(player,now-60000).first();if(recent.count>=8)return json({error:'Too many restarts. Try again in a minute.'},429);const id=crypto.randomUUID(),seed=dailySeed(dayString(now),data.mode);await db(env).batch([db(env).prepare('DELETE FROM runs WHERE created_at < ?').bind(now-DAY),db(env).prepare('INSERT INTO runs (id, player_id, mode, seed, created_at, submitted) VALUES (?, ?, ?, ?, ?, 0)').bind(id,player,data.mode,seed,now)]);return json({id,seed,day:dayString(now)},201,{'Set-Cookie':`hormuz_player=${player}; Path=/; HttpOnly; SameSite=Strict; Max-Age=31536000${url.protocol==='https:'?'; Secure':''}`})}
  if(url.pathname==='/api/scores'){const data=await body(request),player=playerId(request);const name=typeof data.name==='string'?data.name.normalize('NFKC').trim().replace(/\s+/g,' '):'';if(!/^[\p{L}\p{N} _.-]{2,18}$/u.test(name))return json({error:'Use 2–18 letters, numbers, spaces, dots, dashes or underscores.'},400);if(!player||typeof data.runId!=='string')return json({error:'Start a new ranked run.'},400);const run=await db(env).prepare('SELECT * FROM runs WHERE id = ? AND player_id = ?').bind(data.runId,player).first();if(!run)return json({error:'Run expired. Start a new run.'},404);if(run.submitted)return json({saved:true,alreadySaved:true});if(Date.now()-run.created_at>DAY)return json({error:'This run has expired.'},400);
   let verified;try{verified=replay(run.seed,run.mode,data.records,data.ticks)}catch{return json({error:'The run could not be verified. Your next run can be submitted.'},400)}if(verified.time*1000>Date.now()-run.created_at+2500)return json({error:'This run finished faster than the game allows.'},400);
   await db(env).batch([db(env).prepare('INSERT INTO scores (player_id, mode, name, score, duration, won, created_at) VALUES (?, ?, ?, ?, ?, ?, ?) ON CONFLICT(player_id, mode) DO UPDATE SET name = excluded.name, score = excluded.score, duration = excluded.duration, won = excluded.won, created_at = excluded.created_at WHERE CAST(excluded.created_at / 86400000 AS INTEGER) > CAST(scores.created_at / 86400000 AS INTEGER) OR (CAST(excluded.created_at / 86400000 AS INTEGER) = CAST(scores.created_at / 86400000 AS INTEGER) AND excluded.score >= scores.score)').bind(player,run.mode,name,verified.score,Math.floor(verified.time),verified.win?1:0,run.created_at),db(env).prepare('UPDATE runs SET submitted = 1 WHERE id = ? AND player_id = ?').bind(run.id,player)]);const dayStart=Math.floor(run.created_at/DAY)*DAY;const result=await db(env).prepare('SELECT COUNT(*) + 1 AS rank FROM scores WHERE mode = ? AND created_at >= ? AND created_at < ? AND score > ?').bind(run.mode,dayStart,dayStart+DAY,verified.score).first();return json({saved:true,score:verified.score,rank:result.rank,day:dayString(run.created_at)})
  }
 }
 if(url.pathname.startsWith('/api/'))return json({error:'Not found.'},404);
 if(!['GET','HEAD'].includes(request.method))return new Response('Method not allowed',{status:405});const file=assets[url.pathname==='/'?'/index.html':url.pathname];if(!file)return new Response('Not found',{status:404});return new Response(request.method==='HEAD'?null:file.body,{headers:{'Content-Type':file.type,'Cache-Control':'public, max-age=60','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin'}});
 }catch(error){console.error('Game request failed:',error.message);return json({error:'Leaderboard unavailable. Please try again.'},503)}}};
